version: "3.7"

services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - "./docker/nginx/conf.d/webface.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/app/src:/var/www/html"
    ports:
      - "80:80"
    networks:
      - webnet

  php-fpm:
    image: php:fpm-alpine
    restart: always
    volumes:
      - "./docker/app/src:/var/www/html"
      - "/etc/passwd:/etc/passwd"
      - "/etc/group:/etc/group"
      - "./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf"
    expose:
      - "9000"
    networks:
      - webnet

  db:
    image: mysql:5
    restart: always
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
      - "./docker/mysql/custom.cnf:/etc/mysql/mysql.conf.d/custom.cnf"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
    - webnet

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
    - webnet

networks:
  webnet: