version: "3.7"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - "./docker/nginx/conf.d/laravel.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/app:/var/www/html"
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - php-fpm
      - app
  php-fpm:
    image: php:fpm-alpine
    volumes:
      - "./docker/app:/var/www/html"
    networks:
      - webnet
    depends_on:
      - app
  app:
    build: ./docker/src
    volumes:
      - "./docker/app:/var/www/html"

networks:
  webnet:

