version: "3.7"

services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - "./docker/nginx/conf.d/laravel.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/app/src:/var/www/html"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet
    depends_on:
      - php-fpm
      - app
  php-fpm:
    image: php:fpm-alpine
    restart: always
    volumes:
      - "./docker/app/src:/var/www/html"
    expose:
      - "9000"
    networks:
      - webnet
    depends_on:
      - app
  db:
    image: mysql:5
    restart: always
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  app:
    build: ./docker/app
    volumes:
      - "./docker/app/src:/var/www/html"
    expose:
      - "9000"

networks:
  webnet:

